version: '3'
services:
  api:
    build:
      context: ./app/fast-api-implementation
    env_file:
      - config.env
    network_mode: "host"
    ports:
      - "8000:8000"
    depends_on:
      - database
      - broker
      - backend

  worker:
    build:
      context: ./app/celery-remote-worker
    env_file:
      - config.env
    depends_on:
      - database
      - broker
      - backend

  database:
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    ports:
      - "1433:1433"
    env_file:
      - db_config.env

  broker:
    image: rabbitmq

  backend:
    image: redis